### GET All Blogs
GET http://localhost:3001/api/blogs
Accept: application/json

### POST a New BlogModel
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyOWFkNTUyNDdhYzFjMTYyMjIwNjAzMCIsImlhdCI6MTY1NDMyMjg2MCwiZXhwIjoxNjU0MzI2NDYwfQ.89EsgIkOH6bpBnMC7fqHTclb7L5zxtXkRIiPeaHwAcc


{
  "title": "Test Test 2",
  "author": "T. Simons",
  "url": "https://nintendo.com/docs/"
}

### DELETE a post
DELETE http://localhost:3001/api/blogs/629ab9d8a56eadad26fa1f1f
Content-Type: application/json

{
  "authorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyOTc4NGI3NjE3ZjlkMGY2NGI5YjQ5ZCIsImlhdCI6MTY1NDMwNjIzNiwiZXhwIjoxNjU0MzA5ODM2fQ.4edcZFqsG6-ob768FP0SOGQoG6cvnh5kknRCh1N3lNo"
}

### UPDATE a blog's like
PUT http://localhost:3001/api/blogs/629ad55247ac1c1622206036

### GET all users
GET http://localhost:3001/api/users

### POST a New User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "test",
  "name": "testName",
  "password": "test"
}

### login in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "secret"
}
