### GET All Blogs
GET http://localhost:3001/api/blogs
Accept: application/json

### POST a New BlogModel
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Celtics in 4",
  "author": "T. Simons",
  "url": "https://nintendo.com/docs/",
  "authorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyOTc4NGI3NjE3ZjlkMGY2NGI5YjQ5ZCIsImlhdCI6MTY1NDI2NzQ1OCwiZXhwIjoxNjU0MjcxMDU4fQ.kzy09CJzeRGAMy9lGJU8NtDaPYl1fc5GR13CPZ2Q7DQ"
}

### POST a New User
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "username": "Clay Pinter",
  "name": "Barkley",
  "password": "simple"
}

### login in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "secret"
}
